name: Main Pipeline

on:
  push:
    branches:
      - main  # Change if you're using a different branch

jobs:
  configure-trustedhosts:
    uses: ./.github/workflows/trusted-hosts.yml

  build-and-deploy:
    needs: configure-trustedhosts
    uses: ./.github/workflows/iis-deploy.yml
